# Generated by Django 3.0.7 on 2020-06-09 21:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20)),
                ('wics', models.CharField(blank=True, max_length=30)),
                ('now_val', models.PositiveIntegerField(default=0)),
                ('diff', models.IntegerField(default=0)),
                ('fluctuation', models.FloatField(default=0.0)),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('news_count', models.PositiveSmallIntegerField()),
                ('most_recent_pub', models.DateTimeField(default=datetime.datetime(2020, 6, 9, 21, 33, 20, 81546))),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='item.StockItem')),
            ],
            options={
                'ordering': ['item'],
            },
        ),
    ]
