# Generated by Django 3.0.7 on 2020-06-09 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknews',
            name='most_recent_pub',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 9, 21, 33, 40, 51526)),
        ),
    ]
