# Generated by Django 3.0.7 on 2020-06-20 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20200609_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocknews',
            name='most_recent_pub',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 20, 13, 9, 1, 583912)),
        ),
        migrations.AlterField(
            model_name='stocknews',
            name='news_count',
            field=models.PositiveIntegerField(),
        ),
    ]
