#!/bin/sh
POSTGRES_USER="dbuser"
POSTGRES_PASSWORD="dbpw1234"
POSTGRES_DB="stockrmd"

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
	CREATE DATABASE $POSTGRES_DB;
	CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
	ALTER ROLE $POSTGRES_USER SET client_encoding TO 'utf8';
	ALTER ROLE $POSTGRES_USER SET default_transaction_isolation TO 'read committed';
	ALTER ROLE $POSTGRES_USER SET timezone TO 'UTC';
	ALTER USER $POSTGRES_USER CREATEDB;
	GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
EOSQL
