values = {'imonth': 0, 'iday': 0, 'approxdate': 'Unknown', 'extended': -1, 'resolution': 0, 'country': 0, 'country_txt': 'Unknown',
          'region': -1, 'region_txt': 'Unknown', 'provstate': 'Unknown', 'city': 'Unknown', 'specificity': -1, 'vicinity': -1,
          'location': 'Unknown', 'summary': 'Unknown', 'crit1': -1, 'crit2': -1, 'crit3': -1, 'doubtterr': -1, 'alternative': 0,
          'alternative_txt': 'Unknown', 'multiple': -1, 'success': -1, 'suicide': -1, 'attacktype1': 9, 'attacktype1_txt': 'Unknwon',
          'attacktype2': 9, 'attacktype2_txt': 'Unknwon', 'attacktype3': 9, 'attacktype3_txt': 'Unknwon', 'targtype1': 20,
          'targtype1_txt': 'Unknown', 'targtype2': 20, 'targtype2_txt': 'Unknown', 'targtype3': 20, 'targtype3_txt': 'Unknown',
          'targsubtype1': 0, 'targsubtype1_txt': 'Not Exist', 'targsubtype2': 0, 'targsubtype2_txt': 'Not Exist', 
          'targsubtype3': 0, 'targsubtype3_txt': 'Not Exist', 'corp1': 'Not Exist', 'target1': 'Not Exist', 'natlty1': 0,
          'natlty1_txt': 'Not Exist', 'corp2': 'Not Exist', 'target2': 'Not Exist', 'natlty2': 0, 'natlty2_txt': 'Not Exist',
          'corp3': 'Not Exist', 'target3': 'Not Exist', 'natlty3': 0, 'natlty3_txt': 'Not Exist', 'gname': 'Unknown',
          'gsubname': 'Unknown', 'gname2': 'Unknown', 'gsubname2': 'Unknown', 'gname3': 'Unknown', 'gsubname3': 'Unknown',
          'motive': 'Not Exist', 'guncertain1': -1, 'guncertain2': -1, 'guncertain3': -1, 'individual': -1, 'nperps': -99,
          'nperpcap': -1, 'claimed': -1, 'claimmode': 10, 'claimmode_txt': 'Unknown', 'claim2': -1, 'claimmode2': 10,
          'claimmode2_txt': 'Unknown', 'claim3': -1, 'claimmode3': 10, 'claimmode3_txt': 'Unknown', 'compclaim': -9,
          'weaptype1': 13, 'weaptype1_txt': 'Unknown', 'weapsubtype1': 0, 'weapsubtype1_txt': 'Not Exist',
          'weaptype2': 13, 'weaptype2_txt': 'Unknown', 'weapsubtype2': 0, 'weapsubtype2_txt': 'Not Exist',
          'weaptype3': 13, 'weaptype3_txt': 'Unknown', 'weapsubtype3': 0, 'weapsubtype3_txt': 'Not Exist',
          'weaptype4': 13, 'weaptype4_txt': 'Unknown', 'weapsubtype4': 0, 'weapsubtype4_txt': 'Not Exist',
          'weapdetail': 'Unknown', 'nkill': -99, 'nkillus': -99, 'nkillter': -99, 'nwound': -99, 'nwoundus': -99, 'nwoundte': -99,
          'property': -9, 'propextent': 4, 'propextent_txt': 'Not Exist', 'propvalue': 0, 'propcomment': 'Not Exist',
          'ishostkid': -9, 'nhostkid': -99, 'nhostkidus': -99, 'nhours': -99, 'ndays': -99, 'divert': 'Unknown',
          'kidhijcountry': 'Unknown', 'ransom': -9, 'ransomamt': -99, 'ransomamtus': -99, 'ransompaid': -99, 'ransompaidus': -99,
          'ransomnote': 'Not Exist', 'hostkidoutcome': 7, 'hostkidoutcome_txt': 'Unknown', 'nreleased': -99, 'addnotes': 'Not Exist',
          'scite1': 'Not Exist', 'scite2': 'Not Exist', 'scite3': 'Not Exist', 'dbsource': 'Not Exist', 'INT_LOG': -1, 'INT_IDEO': -1,
          'INT_MISC': -1, 'INT_ANY': -1, 'related': 'Not Exist'}


columns_shown = ['eventid', 'iyear', 'imonth', 'iday', 'approxdate', 'extended', 'resolution',
     'country_txt', 'region_txt', 'provstate', 'city', 'latitude', 'longitude', 'specificity',
     'vicinity', 'location', 'summary', 'crit1', 'crit2', 'crit3', 'doubtterr', 'alternative_txt',
     'multiple', 'success', 'suicide', 'attacktype1_txt', 'attacktype2_txt', 'attacktype3_txt',
     'targtype1_txt', 'targsubtype1_txt', 'corp1', 'target1', 'natlty1_txt', 'targtype2_txt',
     'targsubtype2_txt', 'corp2', 'target2', 'natlty2_txt', 'targtype3_txt', 'targsubtype3_txt',
     'corp3', 'target3', 'natlty3_txt', 'gname', 'gsubname', 'gname2', 'gsubname2', 'gname3',
     'gsubname3', 'motive', 'guncertain1', 'guncertain2', 'guncertain3', 'individual', 'nperps',
     'nperpcap', 'claimed', 'claimmode_txt', 'claim2', 'claimmode2_txt', 'claim3',
     'claimmode3_txt', 'compclaim', 'weaptype1_txt', 'weapsubtype1_txt', 'weaptype2_txt',
     'weapsubtype2_txt', 'weaptype3_txt', 'weapsubtype3_txt', 'weaptype4_txt', 'weapsubtype4_txt',
     'weapdetail', 'nkill', 'nkillus', 'nkillter', 'nwound', 'nwoundus', 'nwoundte', 'property',
     'propextent_txt', 'propvalue', 'propcomment', 'ishostkid', 'nhostkid', 'nhostkidus', 'nhours',
     'ndays', 'divert', 'kidhijcountry', 'ransom', 'ransomamt', 'ransomamtus', 'ransompaid',
     'ransompaidus', 'ransomnote', 'hostkidoutcome_txt', 'nreleased', 'addnotes', 'scite1',
     'scite2', 'scite3', 'dbsource', 'INT_LOG', 'INT_IDEO', 'INT_MISC', 'INT_ANY', 'related',
     'cluster_id']